// Knowledge Base Audit - 知识库巡检
// 使用: node kb-audit.js [vault-path]

const fs = require("fs");
const path = require("path");

const VAULT_ROOT = process.argv[2] || __dirname;

function getAllFiles(dir) {
    const files = [];
    const items = fs.readdirSync(dir, { withFileTypes: true });
    for (const item of items) {
        if (item.name.startsWith(".") || item.name === "node_modules") continue;
        const fullPath = path.join(dir, item.name);
        if (item.isDirectory()) {
            files.push(...getAllFiles(fullPath));
        } else {
            files.push(fullPath);
        }
    }
    return files;
}

function getAllDirs(dir) {
    const dirs = [];
    const items = fs.readdirSync(dir, { withFileTypes: true });
    for (const item of items) {
        if (item.name.startsWith(".") || item.name === "node_modules") continue;
        const fullPath = path.join(dir, item.name);
        if (item.isDirectory()) {
            dirs.push(fullPath);
            dirs.push(...getAllDirs(fullPath));
        }
    }
    return dirs;
}

function scanVault() {
    const report = {
        timestamp: new Date().toISOString(),
        vaultPath: VAULT_ROOT,
        stats: { totalFiles: 0, totalDirs: 0, mdFiles: 0, otherFiles: 0 },
        issues: {
            emptyDirs: [],
            orphanFiles: [],
            noFrontmatter: [],
            duplicateNames: [],
            invalidChars: [],
            oversized: []
        }
    };
    
    const allFiles = getAllFiles(VAULT_ROOT);
    const allDirs = getAllDirs(VAULT_ROOT);
    
    report.stats.totalFiles = allFiles.length;
    report.stats.totalDirs = allDirs.length;
    
    // 统计文件类型
    for (const f of allFiles) {
        if (f.endsWith(".md")) report.stats.mdFiles++;
        else report.stats.otherFiles++;
    }
    
    // 检查空目录
    for (const d of allDirs) {
        const contents = fs.readdirSync(d);
        if (contents.length === 0) {
            report.issues.emptyDirs.push(d);
        }
    }
    
    // 检查文件名
    const nameCount = {};
    for (const f of allFiles) {
        const basename = path.basename(f);
        const nameLower = basename.toLowerCase();
        if (!nameCount[nameLower]) nameCount[nameLower] = [];
        nameCount[nameLower].push(f);
    }
    for (const [name, paths] of Object.entries(nameCount)) {
        if (paths.length > 1) {
            report.issues.duplicateNames.push({ name, paths });
        }
    }
    
    // 检查异常字符
    const invalidPattern = /[<>:"|?*]/;
    for (const f of allFiles) {
        const basename = path.basename(f, path.extname(f));
        if (invalidPattern.test(basename)) {
            report.issues.invalidChars.push(f);
        }
    }
    
    // 检查大文件
    const MAX_SIZE = 1024 * 1024; // 1MB
    for (const f of allFiles) {
        const stat = fs.statSync(f);
        if (stat.size > MAX_SIZE) {
            report.issues.oversized.push({ file: f, size: stat.size });
        }
    }
    
    return report;
}

const report = scanVault();

// 输出报告
const outputPath = path.join(VAULT_ROOT, "99-Archive", "kb-audit-report-" + report.timestamp.split("T")[0] + ".md");
if (!fs.existsSync(path.dirname(outputPath))) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
}

let md = "---\n";
md += "created: " + report.timestamp.split("T")[0] + "\n";
md += "tags: [audit, report]\n";
md += "type: audit\n";
md += "---\n\n";
md += "# Knowledge Base Audit Report\n\n";
md += "**Date**: " + report.timestamp.split("T")[0] + "\n\n";
md += "## Stats\n\n";
md += "- Total Files: " + report.stats.totalFiles + "\n";
md += "- Markdown Files: " + report.stats.mdFiles + "\n";
md += "- Other Files: " + report.stats.otherFiles + "\n";
md += "- Total Directories: " + report.stats.totalDirs + "\n\n";

md += "## Issues Found\n\n";

md += "### Empty Directories (" + report.issues.emptyDirs.length + ")\n";
for (const d of report.issues.emptyDirs) {
    md += "- " + d.replace(VAULT_ROOT, "") + "\n";
}

md += "\n### Duplicate Names (" + report.issues.duplicateNames.length + ")\n";
for (const dup of report.issues.duplicateNames) {
    md += "- " + dup.name + ":\n";
    for (const p of dup.paths) {
        md += "  - " + p.replace(VAULT_ROOT, "") + "\n";
    }
}

md += "\n### Invalid Characters (" + report.issues.invalidChars.length + ")\n";
for (const f of report.issues.invalidChars) {
    md += "- " + f.replace(VAULT_ROOT, "") + "\n";
}

md += "\n### Oversized Files (" + report.issues.oversized.length + ")\n";
for (const f of report.issues.oversized) {
    md += "- " + f.file.replace(VAULT_ROOT, "") + " (" + (f.size / 1024 / 1024).toFixed(2) + " MB)\n";
}

md += "\n---\n*Generated by Knowledge Base Audit*\n";

fs.writeFileSync(outputPath, md, "utf8");
console.log("Audit report saved to: " + outputPath);
